### ISSUE TITLE
CITE test failure: verify Collections Path Collection Crs Property Contains Default Crs

### ISSUE THREAD

**Issue by aaime** [geoserver/geoserver-ogcapi#16]
With the release data directory, we need to limit the lists of WFS advertised CRS's for teamengine not to try to request CRS transformations between incompatible extents.

When doing so at the root WFSInfo level, we'll get the following failure for the `sf` feature types (`sf:stream`, `sf:archsites`).

```
java.lang.AssertionError: Collection with id 'archsites' at collections path /collections specifies the storageCrs 'http://www.opengis.net/def/crs/EPSG/0/26713' which is not declared in the global list of CRSs
```

![Image](https://github.com/user-attachments/assets/d8852940-246a-4e0b-a08e-c981d9ddb232)

Apparently we're not compliant with [/req/crs/fc-md-storageCrs-valid-value](https://docs.ogc.org/is/18-058r1/18-058r1.html#_storage_crs)

![Image](https://github.com/user-attachments/assets/7ed3641b-3801-4fd1-a4a3-1a7534ab93cd)

The **workaround** is to go layer by layer and set their "Extra SRS codes for WFS capabilities generation" in the layer edit's publishing tab to explicitly include the `storageCrs`. e.g.: 

![Image](https://github.com/user-attachments/assets/89339d14-3597-472c-a888-ace82dd26d0e)

**Question**: shall we leave it as it or enforce the presence of the `storageCrs` in the collection's `crs` array:

```json
{
  "id": "archsites",
  "title": "Spearfish archeological sites",
  "description": "Sample data from GRASS, archeological sites location, Spearfish, South Dakota, USA",
  ...,
  "crs": [
    "http://www.opengis.net/def/crs/OGC/1.3/CRS84",
    "http://www.opengis.net/def/crs/EPSG/0/26713",
    "http://www.opengis.net/def/crs/EPSG/0/4326",
    "http://www.opengis.net/def/crs/EPSG/0/3857"
  ],
  "storageCrs": "http://www.opengis.net/def/crs/EPSG/0/26713"
}
```

**Comment by aaime** [comment]
I would be nice to the user and always include storageCRS, if it's not in the limited SRS list.
That way an admin can configure a list of common target CRSs without having to tweak each single layer.

**Comment by groldan** [comment]
yes I agree.
How about then we split #2 in two, one would be running the tests, another one passing the tests. It's also already implementing #8 so I wouldn't matter closing two tickets and move on to make this enhancement.

Also, since the workflow will run on pull requests, I think you'd (or any other repo admin) would need to tweak something for it not to prevent pr merges when it fails? or do we rather will make it mandatory?

**Comment by aaime** [comment]
I'm good with merging now and allowing it to fail for the time being.
Once it's fixed however, we should make passing the workflow mandatory.

**Comment by aaime** [comment]
PR here: https://github.com/geoserver/geoserver/pull/8020
