### ISSUE TITLE
Execute, pass and automate CITE tests

### ISSUE THREAD

**Issue by aaime** [geoserver/geoserver-ogcapi#2]
During 2023 GeoServer OGC API Features has already passed once CITE tests for:
* OGC API Features - Part 1, core
* OGC API Features - Part 2, CRS by reference (this second seems to be covered only by the beta site https://cite.ogc.org/te2/ )

The tests assume no data, which means the data is a moving part: changing the data might change the results!
There are also several known issues with the tests themselves: https://github.com/opengeospatial/ets-ogcapi-features10/issues

A few useful links:

* Online teamengine:
   * Official:  https://cite.ogc.org/teamengine/
   * Beta: https://cite.ogc.org/te2/
* The test server that passed CITE last year: https://geonovum.geosolutionsgroup.com/geoserver
* Docker runner for Teamengine: https://github.com/opengeospatial/teamengine-docker
* OGC API Features ETS: https://github.com/opengeospatial/ets-ogcapi-features10

Have an easy way to run it locally.

**Comment by groldan** [comment]
Apparently the docker image only allows you to run team engine locally, but then you have to browse the web interface, login, select the test suite to run, etc. So less useful for automation. I'll give a shot at running the jar file as [mentioned here](https://cite.ogc.org/te2/about/ogcapi-features-1.0/1.0/site/):
```
java -jar ets-ogcapi-features10-1.7.1-aio.jar [-o|--outputDir $TMPDIR] [-h|--generateHtmlReport] [test-run-props.xml]
```

**Comment by groldan** [comment]
Pull request ready for review: https://github.com/geoserver/geoserver/pull/8017
I've split adding the data directory as a separate commit to the one that matters is easier to review in isolation
