### ISSUE TITLE
Setting Up CI/CD Pipelines or Github actions

### ISSUE THREAD

**Issue by aaime** [geoserver/geoserver-ogcapi#8]
We need to establish and integrate continuous integration and deployment pipelines for automated testing. These pipelines should run CITE conformance tests and additional integration tests (e.g., against PostGIS).

Andrea's personal note: if at all possible, I would run this as a Github action, once we let changes in it's harder to get developers to pay attention.

This week:

* [ ] this week: short term make a gitub workflow to run ogcapi-features tests to run unit tests

Long term:
* [ ] Integration tests and CITE Team Engine

**Comment by groldan** [comment]
Github actions workflow set up as part of https://github.com/geoserver/geoserver/pull/8017 from #2 

This is the workflow file: [cite.yml](https://github.com/geoserver/geoserver/pull/8017/files#diff-2fc2398b43026aaa3156bf9e8d222cb0ab93c1e9823eab4ae8d313cf26990e1f)

It'll also run the previous tests that still pass:

![Image](https://github.com/user-attachments/assets/f6be1f42-35ee-4db5-9633-f28202bc4bba)
