### ISSUE TITLE
Update Features Part 3, filtering to finalized specification

### ISSUE THREAD

**Issue by aaime** [geoserver/geoserver-ogcapi#9]
The spec has been finalized:
https://docs.ogc.org/is/19-079r2/19-079r2.html

GeoServer implementation is based on an earlier draft, we need to check if it's still aligned.
While there is not CITE tests for this yet, we should be able to eventually leverage the [ATS](https://docs.ogc.org/is/19-079r2/19-079r2.html#ats) to check, either manually or by JUnit, if the API is compliant.

**Comment by jodygarnett** [comment]
discussion: Can add tests as needed

**Comment by aaime** [comment]
Pull request here: https://github.com/geoserver/geoserver/pull/8016

@jodygarnett checked the ATS, most tests were already there or very close to what the ATS was asking for, added the few missing bits
